import java.time.format.*
import org.apache.tools.ant.taskdefs.condition.Os

// jdkRoot=/Library/Java/JavaVirtualMachines/jdk-25.0.1+8/Contents/Home
// export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-25.0.1+8/Contents/Home

plugins {
    id 'java'
    id 'jacoco'
    id 'distribution'
    id 'checkstyle'
}

assert JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_25)

group = 'org.fife'

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = 'https://central.sonatype.com/repository/maven-snapshots/'
    }
}

wrapper {
    gradleVersion = '9.2.1'
    distributionType = Wrapper.DistributionType.ALL
}

checkstyle {
    toolVersion = '13.0.0'
    configDirectory = file("$rootProject.projectDir/config/checkstyle")
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    reports {
        xml.required = true // codecov depends on xml format report
        html.required = true
    }
}

configurations.all { // Check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

dependencies {

    implementation 'tools.jackson.core:jackson-core:3.0.3'
    implementation 'tools.jackson.core:jackson-databind:3.0.3'
    implementation 'com.formdev:flatlaf:3.7'

    implementation('com.fifesoft.rtext:fife.common:6.0.1') { changing = true }
    implementation('com.fifesoft:rsyntaxtextarea:3.6.1')
    implementation('com.fifesoft:autocomplete:3.3.3')
    implementation('com.fifesoft:rstaui:3.3.2')
    implementation('com.fifesoft:spellchecker:3.4.1')

    testImplementation platform('org.junit:junit-bom:6.0.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.21.0'
}

processResources {
    doLast {
        new File("${buildDir}/resources/main/", 'build-date.txt').text = ZonedDateTime.now( ZoneOffset.UTC ).format( DateTimeFormatter.ISO_INSTANT )
    }
}

compileJava {
    options.release = Integer.parseInt(project.javaVersion)
    options.debug = true
    options.debugOptions.debugLevel = 'source,vars,lines'
    options.compilerArgs << '-Xlint:deprecation' << '-Xlint:unchecked'
}

jar {
    manifest {
        attributes(
            'Specification-Title': 'edisen',
            'Specification-Version': archiveVersion,
            'Implementation-Title': 'org.fife.edisen',
            'Implementation-Version': archiveVersion,
            'Build-Date': Instant.now().toString(),
            'Main-Class': 'org/fife/edisen/ui/Main',
            'Enable-Native-Access': 'ALL-UNNAMED', // Needed for flatlaf, see https://github.com/JFormDesigner/FlatLaf/issues/1035
            'Class-Path': configurations.runtimeClasspath.collect {
                return it.name
            }.join(' ')
        )
    }
}

distTar.dependsOn(jar)
distZip.dependsOn(jar)
installDist.dependsOn(jar)

distributions {
    main {

        contents {
            from { [
                'build/libs',
                configurations.runtimeClasspath // Include gradle dependencies
            ]}
            into { 'lib/' }
        }
    }
}

test {
    useJUnitPlatform()
}


def getWindowsJreDependencyList = { execOps, jdkRoot, installDistDir ->

    // Store the output instead of printing to the console
    def stdout = new ByteArrayOutputStream()

    execOps.exec {
        workingDir installDistDir
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            commandLine "${jdkRoot}/bin/jdeps", '--multi-release', project.javaVersion, '--ignore-missing-deps', '--list-deps', 'lib/edisen*.jar', 'lib/fife.common*.jar', 'lib/flatlaf*.jar', 'lib/jackson*.jar'
        }
        else {
            commandLine '/bin/bash', '-c', "${jdkRoot}/bin/jdeps --multi-release ${javaVersion} --ignore-missing-deps --list-deps lib/edisen*.jar lib/bife.common*.jar lib/flatlaf*.jar lib/jackson*.jar"
        }
        standardOutput = stdout
    }

    def retVal =  String.join(',', stdout.toString().split('[ \t\r\n]+'))
    if (retVal[0] == ',') {
        retVal = retVal.substring(1)
    }
    return retVal
}

tasks.register('generateWindowsJre') {
    dependsOn('build', 'installDist')
    doLast {

        def installDistDir = 'build/install/edisen'
        def execOps = services.get(org.gradle.process.ExecOperations)

        def moduleList = getWindowsJreDependencyList(execOps, jdkRoot, installDistDir)
        println "Generating JRE with modules: ${moduleList}"

        execOps.exec {
            workingDir installDistDir
            commandLine "${jdkRoot}/bin/jlink", '--module-path', "\"${jdkRoot}/jmods\"", '--add-modules',
                    moduleList, '--output', embeddedJreFolderName, '--strip-debug', '--compress', '2',
                    '--no-header-files', '--no-man-pages'
        }
    }
}

tasks.register('generateWindowsStarterExe') {
    dependsOn('generateWindowsJre')
    doLast {
        def execOps = services.get(org.gradle.process.ExecOperations)
        execOps.exec {
            commandLine launch4jExe, 'launch4j.xml'
        }
    }
}

tasks.register('generateMacApp') {
    dependsOn('build', 'installDist')
    doLast {
        def execOps = services.get(org.gradle.process.ExecOperations)
        execOps.exec {
            commandLine '/bin/bash', '-c', './mac/build-mac-app.sh'
        }
    }
}
